# Generated by Django 2.2.1 on 2019-05-06 10:51

from django.db import migrations, models

import Core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPaddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('ipaddress', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('os', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipid', models.IntegerField(default=0)),
                ('port', models.IntegerField(default=0)),
                ('service', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('info', Core.models.DiyDictField(default={})),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('domain', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
