# Generated by Django 2.2.1 on 2019-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTechModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
