# Generated by Django 2.2.1 on 2019-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0002_websitetechmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteWafModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(default=0)),
                ('hasWaf', models.CharField(blank=True, max_length=200, null=True)),
                ('waf', models.CharField(blank=True, max_length=200, null=True)),
                ('detect_tech', models.CharField(blank=True, max_length=200, null=True)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
