# Generated by Django 2.2.1 on 2019-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0003_websitewafmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitewafmodel',
            name='hasWaf',
            field=models.BooleanField(default=None),
        ),
    ]
