# Generated by Django 2.2.1 on 2019-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0004_auto_20190509_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitewafmodel',
            name='hasWaf',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
