# Generated by Django 2.2.1 on 2019-05-17 16:21

from django.db import migrations, models

import Core.models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0005_auto_20190509_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCDNModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(default=0)),
                ('hascdn', models.BooleanField(blank=True, default=None, null=True)),
                ('ipaddress', Core.models.DiyListField(default=[])),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='alive',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
