# Generated by Django 2.2.1 on 2019-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0006_auto_20190517_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecdnmodel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
