# Generated by Django 2.2.1 on 2019-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0007_websitecdnmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='domain',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
