# Generated by Django 2.2.1 on 2019-06-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Data', '0008_ipaddressmodel_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='update_time',
            field=models.IntegerField(default=0),
        ),
    ]
